### ISSUE TITLE
Failures to run acceptance tests/publishing when creating a release

### ISSUE THREAD

**Issue by mhdawson** [paketo-community/ubi-base-stack#46]
Failure here - https://github.com/paketo-community/ubi-base-stack/actions/runs/8070665351/job/22053877535

strange since the tests ran/passed when run on the PR itself.

@pacostas can you take a look?

**Comment by pacostas** [comment]
Yeap, opened PR https://github.com/paketo-community/ubi-base-stack/pull/49 . what was happening, is that the acceptance tests were trying to use a build image that hasnt been downloaded by the workflow. https://github.com/paketo-community/ubi-base-stack/blob/16cf3741c1c642eb6307845ad26891303da1cf9e/.github/workflows/create-release.yml#L551-L606

**Comment by mhdawson** [comment]
The acceptance tests pass, but now we fail to upload
```
X-Xss-Protection: 1; mode=block
{"message":"Validation Failed","request_id":"F080:21909:16425F:1D811D:65E11279","documentation_url":"https://docs.github.com/rest","errors":[{"resource":"ReleaseAsset","code":"already_exists","field":"name"}]}
Retrying in 16.842089869s
  Uploading asset: build-java-21/run.oci -> ubi-base-stack-0.0.37-run-java-21.oci
Error: failed to upload asset: unexpected response: HTTP/2.0 422 Unprocessable Entity
```

@pacostas any chance this has to do with what we had to change to get the acceptance tests passing in the create release process?  If not I'll take a closer look tomorrow.

**Comment by pacostas** [comment]
interesting because i didnt change anything on the create and push release except the upgrade of the actions.

**Comment by pacostas** [comment]
It was uploading twice the 21 java image and therefore the name was already exist. Opened PR https://github.com/paketo-community/ubi-base-stack/pull/52 with the fix. It is also tested.

**Comment by mhdawson** [comment]
@pacostas thanks, closing as should be resolved now.
