### ISSUE TITLE
Question: What about java stacks ?

### ISSUE THREAD

**Issue by cmoulliard** [paketo-community/ubi-base-stack#8]
## Question

As the purpose of this stack is to allow to run/build node.js or java runtimes, when is it planned to include the java stacks ?

**Comment by BarDweller** [comment]
Note that this is the stack project, which creates the base images for the builder image, and creates the run images. 
This stack forms only part of the story for building java projects, the builder image has it's its own repo.

As for when? **As soon as possible** =) we already have...

https://github.com/paketo-community/ubi-java-extension 
and
https://github.com/paketo-community/ubi-java-buildpack

We are waiting on PRs to land to settle dependencies between libcnb/libpak/libjvm/pipeline-builder which are being updated to be Go modules with an increased major version. This is not a small task, but is mostly complete. The java extension & buildpack use these libraries for their implementation, and the dust hasn't settled yet with the v2 migration.

Once the libs are updated appropriately, I can update my forks of the two projects above (which have already been updated to the approaches in the v2 libs, but can't yet reference them correctly until the libs are released), and PR the updated content in, which should result in the java extension & buildpack being built & published. 

Once the java extension & buildpacks are published, this project AND the builder image will need small updates to have the stack generate the java run images, and to have the builder include the extension & buildpack.

**Comment by cmoulliard** [comment]
> Note that this is the stack project, which creates the base images for the builder image, and creates the run images. This stack forms only part of the story for building java projects, the builder image has it's its own repo.

+1

**Comment by cmoulliard** [comment]
> and
> https://github.com/paketo-community/ubi-java-buildpack

Is the goal of the ubi-java-buildpack to be aligned with this project : https://github.com/paketo-buildpacks/java ? Why such a question: From a user's perspective it should be interesting that the buildstacks proposed and finally used part of a build plan are equivalent to make the transition from ubuntu to ubi as smart as possible and not a nightmare to understand why we have so much differences, etc

**Comment by BarDweller** [comment]
Indeed.. this has been the plan since the inception of the Paketo UBI images work. 

You may wish to review the RFC at https://github.com/paketo-buildpacks/rfcs/blob/main/text/0056-ubi-based-stacks.md

**Comment by mhdawson** [comment]
I believe this can be closed as Java has been added.

**Comment by mhdawson** [comment]
closing as Java stacks have been added.
