### ISSUE TITLE
Include images.json file in base image

### ISSUE THREAD

**Issue by mhdawson** [paketo-community/ubi-base-stack#88]
We should copy images.json it into '/etc/buildpacks/images.json'.

It should be owned by root, and the permissions be set to 744.

The plan is to use it in the extensions to find the run images instead of data into the extension.toml

**Comment by cmoulliard** [comment]
> It should be owned by root, and the permissions be set to 744.

Why owned by root and why 744 as the file should not be executable ?

**Comment by pacostas** [comment]
Just a little bit of context, we dont execute the file, we only read its content.

**Comment by cmoulliard** [comment]
> Just a little bit of context, we dont execute the file, we only read its content.

So then permissions should be 644 and not 744 !

**Comment by pacostas** [comment]
I see, thank you :) I'll test and open PR

**Comment by mhdawson** [comment]
Agree that 644 makes more sense, @pacostas thanks for taking care of that.

**Comment by mhdawson** [comment]
PR is ready and should land this week so closine.
